apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shreybatra/sample-frontend

          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: cosmocloud-config
                  key: backend-url

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 5175
      targetPort: 5175
      nodePort: 31000
  selector:
    app: frontend
